### ISSUE TITLE
腾讯公司的薪资水平等数据有问题

### ISSUE THREAD

**Issue by minexss11** [AkiyaX/ChangShaCompany#1]
公司为：腾讯

有问题的数据为哪一行：

- D5
- J5
- K5

真实情况为：

- 绝大部分高级的薪资即使用年薪除12都不到25K。薪资水平顶多算是中上。脉脉上有大量的薪资爆料，可做参考。
- 没有房补/包住（实习生才有）
- 在招岗位大部分都是需要做Go的，但是不限制面试者语言

**Comment by warmchang** [comment]
腾讯40~44小时，几乎没有加班 😕

**Comment by AkiyaX** [comment]
@minexss11 感谢提供信息
@warmchang 请问是否可以提供真实情况呢？

**Comment by AkiyaX** [comment]
已更新
